config/routes.rb
Rails.application.routes.draw do

  root "forms#index"

  resources :forms, except: %i[show] do
    scope module: :forms do
      resources :fields, except: %i[show]
      resources :sections, except: %i[show]
      resource :preview, only: %i[show create]
      resource :load, only: %i[show create]
      resources :data
      resources :configurations_forms
    end
  end

  resources :fields, only: %i[] do
    scope module: :fields do
      resource :validations, only: %i[edit update]
      resource :options, only: %i[edit update]
    end
  end

  resources :nested_forms, only: %i[] do
    scope module: :nested_forms do
      resources :fields, except: %i[show]
    end
  end

end

app/controllers/forms/application_controller.rb
class Forms::ApplicationController < ApplicationController
  layout "forms"

  before_action :set_form

  protected

    def set_form
      @form = Document::Form.find(params[:form_id])
    end

    def set_form_with_eager_load_fields_and_sections
      @form = Document::Form.includes(:sections, :fields).find(params[:form_id])

      grouped_fields = @form.fields.group_by(&:section_id)
      @form.sections.each do |section|
        association = section.fields.instance_variable_get(:@association)
        association.target.concat grouped_fields.fetch(section.id, []).sort_by(&:position)
        association.loaded!
      end
    end
end

app/controllers/forms/configurations_forms_controller.rb
class Forms::ConfigurationsFormsController < Forms::ApplicationController
  before_action :set_configuration, only: %i[show edit update destroy]
  before_action :criteria_builder, only: %i[new create edit update]

  def index
    @configurations = Configurations::Form.where(:configurable => @form).all
  end

  def new
    @configuration = Configurations::Form.new(configurable: @form)
  end

  def edit; end

  def create
    @configuration = Configurations::Form.new(configuration_params)
    @configuration.configurable = @form
    @configuration.data.assign_attributes(data_params)
    if @configuration.data.valid? && @configuration.save
      redirect_to form_configurations_forms_path(@form), notice: "Search configuration was successfully created."
    else
      render :new
    end
  end

  def update
    @configuration.data.assign_attributes(data_params)
    if @configuration.data.valid? && @configuration.update(configuration_params)
      redirect_to form_configurations_forms_path(@form), notice: "Search configuration was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @configuration.destroy
    redirect_to form_configurations_forms_path(@form), notice: "Search configuration was successfully destroyed."
  end

  private

    def set_configuration
      @configuration = Configurations::Form.where(:configurable => @form).find(params[:id])
    end

    def criteria_builder
      @criteria_builder ||= virtual_model.build_criteria_template(@form)
    end

    def virtual_model
      @virtual_model ||= @form.to_virtual_model
    end

    def configuration_params
      params.fetch(:configuration, {}).permit(:name)
    end

    def data_params
      (params.dig(:configuration, :data) || {}).permit(clauses_attributes: [:ignore_blank_values, :field, :type, :comparison_operator, :logical_operator, :label, :placeholder, :namespace, choices_attributes: [:label, :value]])
    end

end

app/controllers/forms/data_controller.rb
class Forms::DataController < Forms::ApplicationController
  before_action :set_form_with_eager_load_fields_and_sections, except: [:show]
  before_action :activate_step_form, only: [:new, :create, :edit, :update]
  before_action :data, only: [:show, :edit, :update, :destroy]
  before_action :criteria_builder, only: [:index]
  before_action :query_builder_templates, only: [:index]

  def index
    if params[:search].present?
      @data = model.lazy_search(params[:search])
    else
      if params[:heavy_search].present?
        @data = model.search(params[:heavy_search])
      else
        if params[:advanced_search].present?
          @data = model.run_advanced_search advanced_search_params
        elsif params[:simple_advanced_search].present?
          @data = model.run_advanced_search simple_advanced_search_params
        else
          @data = model.all
        end
      end
    end
    @data = @data.page(params[:page]).per(1)
  rescue => e
    debugger
  end

  def new
    @data = model.new
  end

  def create
    @data = model.new data_params
    if @data.save
      if @form.step && step.present?
        unless last_step
          return redirect_to edit_form_datum_path(@form, @data, {step: step.to_i + 1})
        end
      end
      redirect_to form_datum_path(@form, @data), notice: "Data was successfully created."
    else
      render :new
    end
    rescue => e
      debugger
  end

  def show
  end

  def edit
  end

  def update
    if @data.update data_params
      if @form.step && step.present?
        unless last_step
          return redirect_to edit_form_datum_path(@form, @data, {step: step.to_i + 1})
        end
      end
      redirect_to form_datum_path(@form, @data), notice: "Data was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    data.destroy
    redirect_to form_data_path, notice: "Data was successfully destroyed."
  end

  private

    def model
      @model ||= @form.to_virtual_model
    end

    def data_params
      params.fetch(:data, {}).permit!
    end

    def data
      return @data if @data
      @data = model.find(params[:id])
      if(step)
        @data.set_current_step(step.to_i)
      end
      @data
    end

    def criteria_builder
      @criteria_builder ||= model.build_criteria_template(@form)
    end

    def query_builder_templates
      @query_builder_templates ||= Configurations::Form.where(configurable: @form).all
    end

    def advanced_search_params
      (params.permit![:advanced_search] || []).map(&:to_h)
    end

    def simple_advanced_search_params
      (params.permit![:simple_advanced_search] || []).map(&:to_h)
    end

    def step
      params[:step]
    end

    def last_step
      step.to_i + 1 == @form.step_options.total
    end

    def first_step
      step.to_i == 0
    end

    def activate_step_form
      if @form.step
        if step
          @form.activate_step step.to_i
        else
          @form.activate_step_from_uid params[:id]
        end
      end
    end

end

app/controllers/forms/fields_controller.rb
class Forms::FieldsController < Forms::ApplicationController
  before_action :set_field, only: %i[show edit update destroy]

  def index
    @fields = @form.fields.includes(:section).rank(:position).all
  end

  def new
    @field = @form.fields.build
  end

  def edit; end

  def create
    @field = @form.fields.build(field_params)
    if @field.save
      redirect_to form_fields_url(@form), notice: "Field was successfully created."
    else
      render :new
    end
  end

  def update
    if @field.update(field_params)
      redirect_to form_fields_url(@form), notice: "Field was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @field.destroy
    redirect_to form_fields_url(@form), notice: "Field was successfully destroyed."
  end

  private

    def set_field
      @field = @form.fields.find(params[:id])
    end

    def field_params
      params.fetch(:field, {}).permit(:name, :label, :hint, :section_id, :accessibility, :type)
    end
end

app/controllers/forms/loads_controller.rb
class Forms::LoadsController < Forms::ApplicationController
  skip_before_action :set_form, except: [:show]
  before_action :set_form_with_eager_load_fields_and_sections, except: [:show]
  before_action :set_preview, except: [:show]

  def show; end

  def create
  end

  private

    def set_preview
      @preview = @form.to_virtual_model
    end

    def serialized_form_data
      params.fetch(:serialized, "")
    end
end

app/controllers/forms/previews_controller.rb
class Forms::PreviewsController < Forms::ApplicationController
  skip_before_action :set_form
  before_action :set_form_with_eager_load_fields_and_sections

  def show
    @instance = instance_id ? model.find(instance_id) : model.new
  end

  def create
    @instance = @preview.new(preview_params)
    @instance.form_id = @form.id
    if @instance.save
      render :create
    else
      render :show
    end
  end

  private

    def instance_id
      params[:instance_id]
    end

    def model
      @model ||= @form.to_virtual_model
    rescue => e
      logger.error(e.backtrace)
      raise e
    end

    def model_params
      params.fetch(:model, {}).permit!
    end

end

app/controllers/forms/sections_controller.rb
class Forms::SectionsController < Forms::ApplicationController
  before_action :set_section, only: %i[show edit update destroy]

  def index
    @sections = @form.sections.all
  end

  def new
    @section = @form.sections.build
  end

  def edit; end

  def create
    @section = @form.sections.build(section_params)

    if @section.save
      redirect_to form_sections_url(@form), notice: "Section was successfully created."
    else
      render :new
    end
  end

  def update
    if @section.update(section_params)
      redirect_to form_sections_url(@form), notice: "Section was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @section.destroy
    redirect_to form_sections_url(@form), notice: "Section was successfully destroyed."
  end

  private

    def set_section
      @section = @form.sections.find(params[:id])
    end

    def section_params
      params.fetch(:section, {}).permit(:title, :headless)
    end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  layout "application"

  before_action :set_form, only: %i[edit update destroy]

  def index
    @forms = Document::Form.all
  end

  def new
    @form = Document::Form.new
  end

  def edit; end

  def create
    @form = Document::Form.new(form_params)
    if @form.save
      redirect_to form_fields_url(@form), notice: "Form was successfully created."
    else
      render :new
    end
  end

  def update
    if @form.update(form_params)
      redirect_to form_fields_url(@form), notice: "Form was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @form.destroy
    redirect_to forms_url, notice: "Form was successfully destroyed."
  end

  private

    def set_form
      @form = Document::Form.find(params[:id])
    end

    def form_params
      params.fetch(:form, {}).permit(:title, :name, :description, :step, step_options: [:non_linear])
    end
end

app/views/forms/configurations_forms/_form.html.erb
<%= form_with(model: [form, configuration], scope: :configuration, local: true) do |f| %>

  <%= display_error_validations configuration %>

  <fieldset data-behaviour="vue">
    <div class="mb-3">
      <%= f.label :name, class: "form-label", for: "form-name" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
      <div class="form-text">
        Configuration name
      </div>
    </div>
    <div class="mb-3">
      <div class="form-text">
        The blank values clause will be ignored if Ignore blank is checked when querying
      </div>
    </div>
    <search-configuration-form :configuration="<%= configuration.to_json %>" url="<%= local_assigns[:url] || request.original_url %>" :params="<%= params.to_json %>" :criteria-template="<%= criteria_template.to_json %>" />
  </fieldset>

  <hr />
  <div class="mt-4">
    <%= f.submit class: "btn btn-primary" %>
  </div>
</fieldset>

<% end %>

app/views/forms/configurations_forms/edit.html.erb
<div class="row gy-3">
  <div class="col-12 d-flex justify-content-between">
    <h2>Edit Search Configuration</h2>
    <%= link_to "Back", form_configurations_forms_path(@form), class: "btn btn-secondary"%>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <%= render "form", form: @form, configuration: @configuration, criteria_template: @criteria_builder.clauses %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/forms/configurations_forms/index.html.erb
<div class="row gy-3">
  <div class="col-12 d-flex justify-content-between">
    <h2>Search Configurations</h2>
    <%= link_to "New Configuration", new_form_configurations_form_path(@form), class: "btn btn-primary"%>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" width="60%">Name</th>
                  <th scope="col" width="20%">Last Update</th>
                  <th scope="col" width="20%"></th>
                </tr>
              </thead>
              <tbody>
                <% @configurations.each do |config| %>
                  <tr>
                    <td><%= config.name %></td>
                    <td><%= config.updated_at %></td>
                    <td>
                      <%= link_to "Edit", edit_form_configurations_form_path(@form, config), class: "btn btn-success text-light" %>
                      <%= link_to "Destroy", form_configurations_form_path(@form, config), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/forms/configurations_forms/new.html.erb
<div class="row gy-3">
  <div class="col-12 d-flex justify-content-between">
    <h2>New Search Configuration</h2>
    <%= link_to "Back", form_configurations_forms_path(@form), class: "btn btn-secondary"%>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <%= render "form", form: @form, configuration: @configuration, criteria_template: @criteria_builder.clauses %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>